#!/usr/bin/env node
/**
 * Fetches Alpine.js documentation markdown from the official GitHub repository
 * and writes the content into src/resources/*.ts files.
 *
 * Run: npm run generate
 * Pin a version: ALPINE_REF=v3.14.0 npm run generate
 */

import { writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const RESOURCES_DIR = join(ROOT, 'src', 'resources');

const REF = process.env.ALPINE_REF ?? 'main';
const BASE = `https://raw.githubusercontent.com/alpinejs/alpine/${REF}/packages/docs/src/en`;

// ---------------------------------------------------------------------------
// Doc manifest — maps resource name → ordered list of doc pages to concatenate
// ---------------------------------------------------------------------------

const manifest = {
  directives: [
    'directives/data',
    'directives/init',
    'directives/show',
    'directives/bind',
    'directives/on',
    'directives/text',
    'directives/html',
    'directives/model',
    'directives/modelable',
    'directives/for',
    'directives/transition',
    'directives/effect',
    'directives/ignore',
    'directives/ref',
    'directives/cloak',
    'directives/teleport',
    'directives/if',
    'directives/id',
  ],
  magics: [
    'magics/el',
    'magics/refs',
    'magics/store',
    'magics/watch',
    'magics/dispatch',
    'magics/nextTick',
    'magics/root',
    'magics/data',
    'magics/id',
  ],
  globals: [
    'globals/alpine-data',
    'globals/alpine-store',
    'globals/alpine-bind',
  ],
  plugins: [
    'plugins/mask',
    'plugins/intersect',
    'plugins/persist',
    'plugins/focus',
    'plugins/collapse',
    'plugins/anchor',
    'plugins/morph',
    'plugins/sort',
  ],
} satisfies Record<string, string[]>;

// ---------------------------------------------------------------------------
// Fetch helpers
// ---------------------------------------------------------------------------

async function fetchDoc(path: string): Promise<string> {
  const url = `${BASE}/${path}.md`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status} ${res.statusText}`);
  return res.text();
}

// ---------------------------------------------------------------------------
// Content cleaning
// ---------------------------------------------------------------------------

function clean(markdown: string): string {
  return markdown
    // Strip YAML frontmatter
    .replace(/^---[\s\S]*?---\n*/m, '')
    // Strip HTML demo blocks
    .replace(/<!-- START_VERBATIM -->[\s\S]*?<!-- END_VERBATIM -->\n*/g, '')
    // Strip named anchor tags
    .replace(/<a name="[^"]*"><\/a>\n*/g, '')
    // Trim leading/trailing whitespace
    .trim();
}

// ---------------------------------------------------------------------------
// TypeScript file writer
// ---------------------------------------------------------------------------

function toIdentifier(name: string): string {
  // e.g. "directives" → "directives"
  return name;
}

function writeResource(name: string, content: string): void {
  const identifier = toIdentifier(name);
  const title = name.charAt(0).toUpperCase() + name.slice(1);
  // Escape backticks and template literal placeholders so the content is safe
  // inside a JS template literal string.
  const escaped = content
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
  const output = [
    `// Auto-generated by scripts/generate.ts — do not edit manually.`,
    `// Source: https://github.com/alpinejs/alpine/tree/${REF}/packages/docs/src/en`,
    ``,
    `export const ${identifier} = \`# Alpine.js ${title}`,
    ``,
    escaped,
    `\`;`,
    ``,
  ].join('\n');

  const filePath = join(RESOURCES_DIR, `${name}.ts`);
  writeFileSync(filePath, output, 'utf8');
  console.log(`  ✓ ${filePath.replace(ROOT + '/', '')}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function generate(): Promise<void> {
  console.log(`Fetching Alpine.js docs from GitHub (ref: ${REF})...\n`);

  mkdirSync(RESOURCES_DIR, { recursive: true });

  for (const [resource, paths] of Object.entries(manifest)) {
    console.log(`Generating ${resource}...`);

    const pages = await Promise.all(paths.map(fetchDoc));

    const content = pages
      .map((raw, i) => {
        const cleaned = clean(raw);
        // Use the last path segment as the section heading if not already present
        const heading = paths[i].split('/').pop()!;
        // The doc files already have an h1 — just separate them with a divider
        return cleaned;
      })
      .join('\n\n---\n\n');

    writeResource(resource, content);
  }

  console.log('\nDone.');
}

generate().catch((err) => {
  console.error(err);
  process.exit(1);
});
